name: Build and Push Docker Image to ECR

on: [workflow_dispatch, push]

env:
  ECR_REPO_NAME: easyfundraising

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@latest

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Publish new image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        TAG=${GITHUB_SHA:0:10}
        docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:${TAG} ./Task1
        docker push $ECR_REGISTRY/$ECR_REPO_NAME:${TAG} 
